INSERT INTO final_reports (
    country_office,
    audit_report_title,
    date_of_audit,
    publication_date,
    page_par_reference,
    audit_recommendations,
    lead_body,
    key_issues,
    acceptance_status,
    current_implementation_status,
    target_completion_date,
    follow_up_date,
    recurence,
    action_plan,
    responsible_person,
    sai_confirmation,
    responsible_entity,
    head_of_audited_entity,
    audited_entity_focal_point,
    audit_team_lead,
    summary_of_response,
    responsible_person_email,
    created_at,
    updated_at
) VALUES 
('SAI Kiribati','IT Security Audit','2023/08/20','2023/09/30','Page 15, Paragraph 2','Implement multi-factor authentication.','IT Department','Vulnerabilities in IT systems','Accepted','Ongoing','2024/06/30','2024/12/31','Yes','Upgrade firewall and antivirus software.','Alice Brown','SAI Kiribati','IT Department','David White','Sarah Adams','Michael Turner','Regularly update software patches.', CONCAT('alice.brown@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','IT Security Audit','2023/08/20','2023/09/30','Page 15, Paragraph 2','Train employees on cyber hygiene.','IT Department','Vulnerabilities in IT systems','Accepted','Ongoing','2024/06/30','2024/12/31','Yes','Upgrade firewall and antivirus software.','Alice Brown','SAI Kiribati','IT Department','David White','Sarah Adams','Michael Turner','Regularly update software patches.', CONCAT('alice.brown@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','IT Security Audit','2023/08/20','2023/09/30','Page 15, Paragraph 2','Conduct regular penetration testing.','IT Department','Vulnerabilities in IT systems','Accepted','Ongoing','2024/06/30','2024/12/31','Yes','Upgrade firewall and antivirus software.','Alice Brown','SAI Kiribati','IT Department','David White','Sarah Adams','Michael Turner','Regularly update software patches.', CONCAT('alice.brown@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','Human Resources Audit','2023/11/10','2023/12/15','Page 20, Paragraph 5','Develop a comprehensive training calendar.','HR Department','Inadequate staff development','Accepted','Partially Implemented','2024/09/30','2025/03/31','No','Develop a comprehensive training calendar.','Emily Green','SAI Kiribati','HR Department','Robert Miller','Jennifer Taylor','Andrew Wilson','Monitor employee skill progression.', CONCAT('emily.green@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','Human Resources Audit','2023/11/10','2023/12/15','Page 20, Paragraph 5','Implement mentorship programs.','HR Department','Inadequate staff development','Accepted','Partially Implemented','2024/09/30','2025/03/31','No','Develop a comprehensive training calendar.','Emily Green','SAI Kiribati','HR Department','Robert Miller','Jennifer Taylor','Andrew Wilson','Monitor employee skill progression.', CONCAT('emily.green@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','Human Resources Audit','2023/11/10','2023/12/15','Page 20, Paragraph 5','Establish a performance feedback system.','HR Department','Inadequate staff development','Accepted','Partially Implemented','2024/09/30','2025/03/31','No','Develop a comprehensive training calendar.','Emily Green','SAI Kiribati','HR Department','Robert Miller','Jennifer Taylor','Andrew Wilson','Monitor employee skill progression.', CONCAT('emily.green@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','Human Resources Audit','2023/11/10','2023/12/15','Page 20, Paragraph 5','Conduct regular team-building activities.','HR Department','Inadequate staff development','Accepted','Partially Implemented','2024/09/30','2025/03/31','No','Develop a comprehensive training calendar.','Emily Green','SAI Kiribati','HR Department','Robert Miller','Jennifer Taylor','Andrew Wilson','Monitor employee skill progression.', CONCAT('emily.green@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','Procurement Process Audit','2024/02/18','2024/03/31','Page 12, Paragraph 1','Enhance procurement documentation practices.','Procurement Department','Lack of transparency in procurement','Accepted','Not Implemented','2024/12/31','2025/06/30','No','Enhance procurement documentation practices.','Daniel Lewis','SAI Kiribati','Procurement Department','Olivia Turner','Brian Parker','Sophia Moore','Regularly update procurement guidelines.', CONCAT('daniel.lewis@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','Procurement Process Audit','2024/02/18','2024/03/31','Page 12, Paragraph 1','Implement vendor performance evaluations.','Procurement Department','Lack of transparency in procurement','Accepted','Not Implemented','2024/12/31','2025/06/30','No','Enhance procurement documentation practices.','Daniel Lewis','SAI Kiribati','Procurement Department','Olivia Turner','Brian Parker','Sophia Moore','Regularly update procurement guidelines.', CONCAT('daniel.lewis@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','Procurement Process Audit','2024/02/18','2024/03/31','Page 12, Paragraph 1','Train procurement staff on ethical practices.','Procurement Department','Lack of transparency in procurement','Accepted','Not Implemented','2024/12/31','2025/06/30','No','Enhance procurement documentation practices.','Daniel Lewis','SAI Kiribati','Procurement Department','Olivia Turner','Brian Parker','Sophia Moore','Regularly update procurement guidelines.', CONCAT('daniel.lewis@example.com_', UUID()), '2024-01-25', '2024-01-25'),
('SAI Kiribati','Procurement Process Audit','2024/02/18','2024/03/31','Page 12, Paragraph 1','Establish a procurement oversight committee.','Procurement Department','Lack of transparency in procurement','Accepted','Not Implemented','2024/12/31','2025/06/30','No','Enhance procurement documentation practices.','Daniel Lewis','SAI Kiribati','Procurement Department','Olivia Turner','Brian Parker','Sophia Moore','Regularly update procurement guidelines.', CONCAT('daniel.lewis@example.com_', UUID()), '2024-01-25', '2024-01-25');
